import Image from "next/image";
import { ScrollReadingText } from "@/components/scroll-reading-text";
import { SiteHeader } from "@/components/site-header";

const capabilities = [
  ["Canonical profile", "Your name, bio, photo, links, and brand details live in one source of truth."],
  ["Platform sync", "Update what each connected platform permits. See exactly what needs your attention."],
  ["Identity health", "Spot stale bios, broken links, mismatched images, and public-profile gaps before they cost trust."],
];

export default function Home() {
  return <main className="bg-white text-black"><SiteHeader />
    <section className="mx-auto max-w-[1440px] border-t border-black"><div className="flex min-h-[640px] flex-col items-center justify-between px-5 py-7 text-center sm:px-8 lg:px-12"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#ff4d00]">THE ONLINE IDENTITY OPERATING SYSTEM</p><div className="flex flex-col items-center py-16"><h1 className="max-w-5xl text-[clamp(4.4rem,10vw,9.4rem)] font-black leading-[0.78] tracking-[-0.1em]">ONE PROFILE.<br />EVERY PLATFORM.<br /><span className="text-[#ff4d00]">ALWAYS CURRENT.</span></h1><p className="mt-10 max-w-xl text-lg leading-7 text-black/65 sm:text-xl">Ownlane gives you one source of truth for the identity people find across the internet.</p><a className="button-pour mt-8 inline-flex bg-black px-5 py-4 text-sm font-bold uppercase tracking-[0.09em] text-white [--button-fill:#ff4d00]" href="#how-it-works"><span>See how it works</span></a></div><div className="flex w-full self-stretch items-end justify-between border-t border-black pt-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-black/45">One source. Your whole presence.</p><p className="hidden max-w-xs text-right text-xs font-bold uppercase tracking-[0.12em] text-black/65 sm:block">For people and brands done updating everything twice.</p></div></div></section>
    <section className="mx-auto max-w-[1440px] border-x border-black"><div className="grid lg:grid-cols-[0.9fr_1.1fr]"><div className="flex flex-col justify-between border-b border-black px-5 py-12 sm:px-8 lg:border-b-0 lg:border-r lg:px-12 lg:py-16"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#ff4d00]">YOUR IDENTITY SHOULD NOT DRIFT</p><h2 className="mt-20 max-w-xl text-5xl font-black leading-[0.83] tracking-[-0.08em] sm:text-7xl">The internet changes. You stay recognisable.</h2><p className="mt-10 max-w-md text-lg leading-7 text-black/65">Bios become stale. Links break. A new profile image lands on one account but not another. Ownlane keeps your presence intentional.</p></div><div className="relative min-h-[500px] overflow-hidden bg-black"><Image alt="A person working at a desk" className="object-cover grayscale" fill sizes="(max-width: 1440px) 100vw, 720px" src="/images/creator-strip.png" /><div className="absolute inset-x-0 top-[13%] border-y border-black bg-[#ff4d00] py-3 text-center text-xs font-bold uppercase tracking-[0.16em] text-black">Your identity is more than a button list</div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-0 lg:py-24" id="how-it-works"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-0"><div className="lg:px-12 lg:pr-20"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#ff4d00]">YOUR CONTROL CENTRE</p><h2 className="mt-5 max-w-md text-5xl font-black leading-[0.83] tracking-[-0.08em] sm:text-6xl">Set it once. Know where it stands.</h2></div><div className="border-t border-black">{capabilities.map(([name, detail], index) => <article className="grid grid-cols-[44px_1fr] gap-4 border-b border-black py-6 sm:grid-cols-[64px_1fr] sm:gap-7" key={name}><span className="font-mono text-xs text-[#ff4d00]">0{index + 1}</span><div><h3 className="text-3xl font-black tracking-[-0.06em]">{name}</h3><p className="mt-2 max-w-lg text-lg leading-7 text-black/65">{detail}</p></div></article>)}</div></div><ScrollReadingText>One profile, clear changes, connected platforms, and no guessing about what the world sees.</ScrollReadingText></section>
    <footer className="overflow-hidden border-t border-black pt-5"><div className="mx-auto flex max-w-[1440px] justify-between px-5 text-[10px] font-bold uppercase tracking-[0.12em] sm:px-8"><span>Ownlane © {new Date().getFullYear()}</span><span>One profile. Every platform.</span></div><p className="-mb-[0.15em] mt-4 whitespace-nowrap text-center text-[24vw] font-black leading-none tracking-[-0.12em]">OWNLANE</p></footer>
  </main>;
}
